### PR TITLE
Add two numbers represented by linked lists.java

### PR DESCRIPTION
**Pull request by Anonymous866**
Program name - Add two numbers represented by linked lists
Language used - JAVA

### CODE REVIEW

**Comment by GauravWalia19** [comment]
@Catastrophic866 can you please create a issue also.

**Comment by Catastrophic866** [comment]
> @Catastrophic866 can you please create a issue also.

Yes definitely

**Review by GauravWalia19 — CHANGES_REQUESTED** [review]
Add the code extension .java and update the README.

**Comment by GauravWalia19** [comment]
@Catastrophic866 can you please send all the changes in this PR only.

**Comment by GauravWalia19** [comment]
Thanks for choosing our repository for contributing to Hacktober Fest 20
As a part of the new process this Issue is marked as hacktoberfest-expiry & closed
Please check our new updated contribution guidelines [here](https://github.com/TechOUs/DSKaKhel/blob/master/CONTRIBUTING.md)

**Pull request closed without merging**
